substitutions:
  name: everything-presence-one-708114
  friendly_name: "Capteur Presence Marilou"
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret everything-presence-one-708114-api-encryption-key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password